# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 829)
        MainWindow.setStyleSheet("QMainWindow#MainWindow{\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    border:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"}\n"
"\n"
"QTabWidget#tabWidget{\n"
"    border:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"     background: rgb(225, 211, 235);\n"
"     border: 2px solid #b08bca;\n"
"     border-bottom-color: #b08bca;\n"
"     border-bottom-left-radius: 15px;\n"
"     border-bottom-right-radius: 15px;\n"
"     min-width: 8ex;\n"
"     padding: 10px;\n"
" }\n"
"\n"
"QTabBar::tab_2 {\n"
"     background: rgb(225, 211, 235);\n"
"     border: 2px solid #b08bca;\n"
"     border-bottom-color: #b08bca;\n"
"     border-bottom-left-radius: 15px;\n"
"     border-bottom-right-radius: 15px;\n"
"     min-width: 8ex;\n"
"     padding: 10px;\n"
" }\n"
"\n"
"QTabBar::tab_3 {\n"
"     background: rgb(225, 211, 235);\n"
"     border: 2px solid #b08bca;\n"
"     border-bottom-color: #b08bca;\n"
"     border-bottom-left-radius: 15px;\n"
"     border-bottom-right-radius: 15px;\n"
"     min-width: 8ex;\n"
"     padding: 10px;\n"
" }\n"
"\n"
"QTabBar::tab_4 {\n"
"     background: rgb(225, 211, 235);\n"
"     border: 2px solid #b08bca;\n"
"     border-bottom-color: #b08bca;\n"
"     border-bottom-left-radius: 15px;\n"
"     border-bottom-right-radius: 15px;\n"
"     min-width: 8ex;\n"
"     padding: 10px;\n"
" }\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                 stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
" }\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #5f5adf;\n"
"     border-color: #7d55da;\n"
"     border-bottom-color: #7d55da; \n"
" }\n"
"\n"
"QWidget#tab{\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"}\n"
"\n"
".QHBoxLayout{\n"
"    border:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(".QTabWidget{\n"
"    width: 400px;\n"
"    height: 400px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAutoFillBackground(False)
        self.tab.setStyleSheet(" .QWidget {\n"
" background-color: qlineargradient(spread:pad, x1:1, y1:0.886, x2:0.023, y2:0.317864, stop:0 rgba(151, 149, 174, 255), stop:0.785311 rgba(213, 211, 221, 255))\n"
" }")
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    height: 20px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    height: 30px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_12.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setStyleSheet("")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 22px;\n"
"    min-width: 20px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/minus.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("файлы от вити 2/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(44, 0))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 22px;\n"
"    min-width: 20px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/plus-twitter.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("файлы от вити 2/images/plus-twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(False)
        self.pushButton.setChecked(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.tab)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 22px;\n"
"    min-width: 20px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/minus.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 22px;\n"
"    min-width: 20px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/plus-twitter.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    height: 20px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 30px;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    width: 60px;\n"
"    height: 60px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/plus-twitter.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setStyleSheet(" QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.557, stop:0 rgba(54, 51, 152, 255), stop:0.893258 rgba(167, 99, 110, 255));\n"
"    border-radius: 50px;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    width: 100px;\n"
"    height: 100px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/start.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("файлы от вити 2/images/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_10.addWidget(self.pushButton_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("*{\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_3)
        self.listWidget_3.setStyleSheet("")
        self.listWidget_3.setObjectName("listWidget_3")
        self.horizontalLayout_4.addWidget(self.listWidget_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setStyleSheet(" QPushButton {\n"
"     border: 2px solid #8f8f91;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"    border-radius: 22px;\n"
"    min-width: 20px;\n"
"    width: 40px;\n"
"    height: 40px;\n"
"     image: url(C:/Users/Gamer/Desktop/Проект архив/файлы от вити 2/images/minus.png);\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    border: 1px solid #8f8f91;\n"
"    height: 20px;\n"
"    width: 760px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_8.addWidget(self.comboBox_3)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setStyleSheet(" QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.557, stop:0 rgba(54, 51, 152, 255), stop:0.893258 rgba(167, 99, 110, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    width: 100px;\n"
"    height: 20px;\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setCheckable(False)
        self.pushButton_9.setAutoExclusive(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        
        self.model_2 = QtGui.QStandardItemModel(self)
        self.tableView_2 = QtWidgets.QTableView(self.tab_4)
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_2.setModel(self.model_2)
        self.tableView_2.horizontalHeader().setStretchLastSection(True)
        
        self.horizontalLayout_9.addWidget(self.tableView_2)
        
        self.model_3 = QtGui.QStandardItemModel(self)
        self.tableView_3 = QtWidgets.QTableView(self.tab_4)
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_3.setModel(self.model_3)
        self.tableView_3.horizontalHeader().setStretchLastSection(True)
        
        self.horizontalLayout_9.addWidget(self.tableView_3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    border: 1px solid #8f8f91;\n"
"    height: 20px;\n"
"    width: 760px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_6.addWidget(self.comboBox_2)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border: 1px solid #8f8f91;\n"
"    height: 20px;\n"
"    width: 760px;\n"
"    border-width: 5px;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setStyleSheet(" QPushButton {\n"
"    border: 2px solid #8f8f91;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.551, x2:1, y2:0.557, stop:0 rgba(54, 51, 152, 255), stop:0.893258 rgba(167, 99, 110, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"    width: 150px;\n"
"    height: 20px;\n"
" }\n"
"\n"
" QPushButton:default {\n"
"     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
"    \n"
" }\n"
"\n"
"QPushButton:hover{\n"
"        background-color:rgba(100,255,100, 100);\n"
"        border-color: rgba(255, 225, 255, 200);\n"
"        color:rgba(0, 0, 0, 200);\n"
"}\n"
" \n"
"QPushButton:pressed { \n"
"     background-color:rgba(100,255,100, 200);\n"
"     border-color: rgba(255, 225, 255, 30);\n"
"     border-style: inset;\n"
"     color:rgba(0, 0, 0, 100);\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 500))
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setText("")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 500))
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setText("")
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        
        self.model = QtGui.QStandardItemModel(self)
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setMinimumSize(QtCore.QSize(0, 500))
        self.tableView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView.setObjectName("tableView")
        self.tableView.setModel(self.model)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        
        self.verticalLayout_8.addWidget(self.tableView)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setText(_translate("MainWindow", "Имя"))
        self.lineEdit.setText(_translate("MainWindow", "Описание"))
        self.label.setText(_translate("MainWindow", "генерация"))
        self.label_2.setText(_translate("MainWindow", "Оптимизация"))
        self.lineEdit_5.setText(_translate("MainWindow", "Количество иттераций"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Проведение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Контроль серии"))
        self.pushButton_9.setText(_translate("MainWindow", "Вывести данные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Результаты"))
        self.pushButton_6.setText(_translate("MainWindow", "Вывести статистику"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Статистика"))
